# Generated by Django 4.1 on 2022-09-03 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='symptoms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.symptoms'),
        ),
    ]
