# Generated by Django 4.1 on 2022-09-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profile_symptoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active_cases', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('new_cases', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='symptoms',
            name='serious',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
