# Generated by Django 4.1 on 2022-09-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_city_symptoms_serious'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='symptoms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.symptoms'),
        ),
    ]
