# Generated by Django 4.1 on 2022-09-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_symptoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='profile',
            name='symptoms',
            field=models.ManyToManyField(blank=True, null=True, to='app.symptoms'),
        ),
    ]
