# Generated by Django 4.1 on 2022-09-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profile_symptoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('protection', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='serious',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='weight',
        ),
        migrations.AddField(
            model_name='profile',
            name='certificate',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptoms',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='type',
            field=models.CharField(default='main', max_length=20),
            preserve_default=False,
        ),
    ]
