# Generated by Django 4.1 on 2022-09-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_symptoms_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app'),
        ),
    ]
